---

- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- hosts: nodejs
  sudo: True
  roles:
    - common
    - nodejs

- include: couchbase_main.yml
  # roles:
  #   - common
  #   - couchbase
